from __future__ import annotations

CORE_KEYWORDS = {
    "elastomer": 20,
    "elastomers": 18,
    "polymer": 18,
    "polymers": 18,
    "polymer science": 22,
    "polymer technology": 20,
    "polymer technologist": 20,
    "rubber technology": 18,
    "rubber technologist": 18,
    "material development": 16,
    "materials development": 16,
    "product development": 14,
    "product development materials": 18,
    "product development - material": 18,
    "elastomer expert": 18,
    "elastomer specialist": 18,
    "elastomer development engineer": 62,
    "elastomer engineer": 46,
    "polymer scientist": 60,
    "polymer technology engineer": 52,
    "rubber technology engineer": 64,
    "materials development engineer": 32,
    "compound development engineer": 58,
    "product development engineer materials": 24,
}

RELATED_ELASTOMER_RUBBER_KEYWORDS = {
    "elastomer development": 18,
    "elastomer engineering": 16,
    "elastomer technology": 16,
    "elastomer science": 16,
    "elastomer formulation": 17,
    "elastomer compounding": 17,
    "elastomer compound": 15,
    "rubber development": 16,
    "rubber engineering": 16,
    "rubber technology": 18,
    "rubber science": 16,
    "rubber formulation": 17,
    "rubber compounding": 17,
    "rubber compound": 15,
    "rubber materials": 15,
    "rubber r&d": 14,
    "rubber research": 14,
    "rubber specialist": 15,
    "rubber expert": 15,
    "rubber scientist": 15,
    "epdm": 12,
    "nbr": 12,
    "sbr": 12,
    "fkm": 12,
    "nr": 10,
    "cr": 10,
    "iir": 10,
    "silicone rubber": 12,
    "silicone elastomer": 12,
    "thermoplastic elastomer": 15,
    "tpe": 12,
    "tpu": 12,
    "tpv": 12,
}

POLYMER_KEYWORDS = {
    "polymer engineering": 18,
    "polymer engineer": 19,
    "polymer scientist": 18,
    "polymer science": 22,
    "polymer chemistry": 17,
    "polymer technology": 20,
    "polymer technologist": 20,
    "polymer development": 18,
    "polymer r&d": 15,
    "polymer research": 15,
    "polymer processing": 14,
    "polymer processing technology": 16,
    "polymer materials": 15,
    "polymer materials development": 18,
    "polymer characterization": 13,
    "polymer testing": 12,
    "polymer formulation": 17,
    "polymer compounding": 17,
    "polymer specialist": 15,
    "polymer expert": 15,
}

MATERIALS_KEYWORDS = {
    "materials development": 17,
    "material development": 17,
    "materials engineering": 16,
    "material engineering": 16,
    "materials engineer": 10,
    "material engineer": 10,
    "materials scientist": 15,
    "materials science": 15,
    "materials technology": 14,
    "materials research": 14,
    "materials r&d": 14,
    "material characterization": 13,
    "materials characterization": 13,
    "advanced materials": 12,
    "material innovation": 12,
    "materials innovation": 12,
    "material formulation": 15,
    "compound development": 17,
    "compound formulation": 17,
    "formulation development": 16,
}

PRODUCT_DEVELOPMENT_KEYWORDS = {
    "product development materials": 18,
    "product development polymer": 18,
    "product development elastomer": 18,
    "product development rubber": 18,
    "product development engineer": 15,
    "product development scientist": 15,
    "material product development": 15,
    "materials product development": 15,
    "new product development": 12,
    "npd materials": 14,
    "npd polymer": 14,
    "npd elastomer": 14,
}

RND_KEYWORDS = {
    "r&d": 10,
    "research and development": 12,
    "research & development": 12,
    "research engineer": 12,
    "research scientist": 12,
    "development engineer": 12,
    "development scientist": 12,
    "r&d engineer": 12,
    "r&d scientist": 12,
    "r&d specialist": 12,
    "laboratory development": 10,
    "technical development": 10,
    "technology development": 10,
}

FORMULATION_COMPOUNDING_KEYWORDS = {
    "formulation": 12,
    "formulation development": 16,
    "compound formulation": 17,
    "compound development": 17,
    "compounding": 14,
    "polymer compounding": 16,
    "rubber compounding": 16,
    "elastomer compounding": 16,
    "mixing": 8,
    "rubber mixing": 10,
    "polymer processing": 14,
    "material formulation": 15,
}

GERMAN_KEYWORDS = {
    "elastomer": 18,
    "elastomere": 18,
    "elastomerentwicklung": 18,
    "elastomertechnik": 18,
    "elastomerformulierungen": 18,
    "elastomerformulierung": 18,
    "polymer": 18,
    "polymere": 18,
    "polymerwissenschaft": 18,
    "polymertechnik": 18,
    "polymertechnologie": 18,
    "polymerformulierungen": 18,
    "polymerformulierung": 18,
    "kunststoff": 16,
    "kunststoffe": 16,
    "kunststofftechnik": 20,
    "kunststofftechnologie": 16,
    "kunststoffentwicklung": 16,
    "werkstoffentwicklung": 22,
    "werkstofftechnik": 18,
    "werkstoffwissenschaft": 16,
    "materialentwicklung": 20,
    "materialtechnik": 15,
    "gummitechnik": 16,
    "gummitechnologie": 16,
    "kautschuk": 16,
    "kautschuktechnik": 16,
    "kautschuktechnologie": 16,
    "kautschukentwicklung": 16,
    "mischungsentwicklung": 15,
    "mischungstechnik": 15,
    "compoundierung": 14,
    "produktentwicklung": 14,
    "entwicklung": 10,
    "formulierung": 12,
}

NEGATIVE_CONTEXT_KEYWORDS = {
    "accounting": -25,
    "finance": -25,
    "sales": -20,
    "warehouse": -18,
    "operator": -18,
    "administrative": -15,
    "office": -10,
    "software engineer": -15,
    "mechanical engineer": -5,
    "civil engineer": -5,
}

MATCH_THRESHOLDS = {
    "STRONG_MATCH": 80,
    "GOOD_MATCH": 60,
    "POSSIBLE_MATCH": 40,
    "IRRELEVANT": 39,
}

TITLE_WEIGHT = {
    "high": 1.4,
    "medium": 1.1,
    "low": 0.8,
}
