ELASTOMER_KEYWORDS = [
    "elastomer",
    "rubber",
    "rubber technology",
    "polymer",
    "polymers",
    "polymer science",
    "polymer chemistry",
    "materials development",
    "material development",
    "materials engineer",
    "materials scientist",
    "product development",
    "research and development",
    "r&d",
    "rubber compounds",
    "elastomer compounds",
    "polyurethane",
    "silicone",
    "thermoplastic elastomer",
    "tpe",
    "vulcanization",
    "compounding",
    "polymer processing",
    "materials innovation",
    "technical development",
    "application development",
    "polymer applications",
    "materials testing",
    "formulation development",
    "rubber testing",
    "engineering materials",
]
