DEFAULT_SEARCH_TERMS = [
    "elastomer",
    "elastomers",
    "polymer",
    "polymers",
    "polymer science",
    "polymer technology",
    "polymer technologist",
    "rubber",
    "rubber technology",
    "rubber technologist",
    "material development",
    "materials development",
    "material engineering",
    "materials engineering",
    "product development",
    "product development materials",
    "elastomer expert",
    "elastomer specialist",
    "rubber specialist",
    "polymer engineer",
    "polymer scientist",
    "materials scientist",
    "materials engineer",
    "R&D polymer",
    "R&D elastomer",
    "R&D rubber",
    "formulation",
    "rubber formulation",
    "polymer formulation",
    "compound development",
    "compounding",
    "elastomer development",
    "polymer development",
    "materials development",
    "Elastomer",
    "Elastomere",
    "Elastomerentwicklung",
    "Polymer",
    "Polymere",
    "Polymerwissenschaft",
    "Polymertechnik",
    "Kunststoff",
    "Kunststoffe",
    "Kunststofftechnik",
    "Kunststofftechnologie",
    "Werkstoffentwicklung",
    "Werkstofftechnik",
    "Materialentwicklung",
    "Gummitechnik",
    "Gummitechnologie",
    "Kautschuk",
    "Kautschuktechnik",
    "Kautschuktechnologie",
    "Mischungsentwicklung",
    "Compoundierung",
    "Werkstoffwissenschaft",
    "Produktentwicklung",
    "polymerteknikk",
    "elastomerteknikk",
    "gummi",
    "materialutvikling",
    "materialteknikk",
    "produktutvikling",
    "polymerutvikling",
    "rubber technology",
    "gummiteknologi",
    "polymerteknologi",
]
